export enum CreateLesson {
  CREATE_LESSON_REQUEST = 'CREATE_LESSON_REQUEST',
  CREATE_LESSON_SUCCEEDED = 'CREATE_LESSON_SUCCEEDED',
  CREATE_LESSON_FAILED = 'CREATE_LESSON_FAILED'
}
export enum CreateChapter {
  CREATE_ATTACHMENT_REQUEST = 'CREATE_ATTACHMENT_REQUEST',
  CREATE_ATTACHMENT_SUCCEEDED = 'CREATE_ATTACHMENT_SUCCEEDED',
  CREATE_ATTACHMENT_FAILED = 'CREATE_ATTACHMENT_FAILED'
}
