export enum CreateLesson {
  CREATE_LESSON_REQUEST = 'CREATE_LESSON_REQUEST',
  CREATE_LESSON_SUCCEEDED = 'CREATE_LESSON_SUCCEEDED',
  CREATE_LESSON_FAILED = 'CREATE_LESSON_FAILED',
}

export enum UpdateLesson {
  UPDATE_LESSON_REQUEST = 'UPDATE_LESSON_REQUEST',
  UPDATE_LESSON_SUCCEEDED = 'UPDATE_LESSON_SUCCEEDED',
  UPDATE_LESSON_FAILED = 'UPDATE_LESSON_FAILED',
}

export enum DeleteLesson {
  DELETE_LESSON_REQUEST = 'DELETE_LESSON_REQUEST',
  DELETE_LESSON_SUCCEEDED = 'DELETE_LESSON_SUCCEEDED',
  DELETE_LESSON_FAILED = 'DELETE_LESSON_FAILED',
}

export enum CreateAttachment {
  CREATE_ATTACHMENT_REQUEST = 'CREATE_ATTACHMENT_REQUEST',
  CREATE_ATTACHMENT_SUCCEEDED = 'CREATE_ATTACHMENT_SUCCEEDED',
  CREATE_ATTACHMENT_FAILED = 'CREATE_ATTACHMENT_FAILED',
}
export enum DeleteAttachment {
  DELETE_ATTACHMENT_REQUEST = 'DELETE_ATTACHMENT_REQUEST',
  DELETE_ATTACHMENT_SUCCEEDED = 'DELETE_ATTACHMENT_SUCCEEDED',
  DELETE_ATTACHMENT_FAILED = 'DELETE_ATTACHMENT_FAILED',
}

export interface Attachment {
  createdAt: string
  description: string
  lesson: string
  number: number
  status: number
  title: string
  updatedAt: string
  url: string
  _id: string
}
