
export enum CreateCourse {
  CREATE_COURSE_REQUEST = 'CREATE_COURSE_REQUEST',
  CREATE_COURSE_SUCCEEDED = 'CREATE_COURSE_SUCCEEDED',
  CREATE_COURSE_FAILED = 'CREATE_COURSE_FAILED'
}

export enum GetCourseById {
  GET_COURSE_REQUEST = 'GET_COURSE_REQUEST',
  GET_COURSE_SUCCEEDED = 'GET_COURSE_SUCCEEDED',
  GET_COURSE_FAILED = 'GET_COURSE_FAILED'
}
